// <auto-generated />
namespace PrimePaper.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addedDescriptionanddeletedtheicondeleteincontract : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedDescriptionanddeletedtheicondeleteincontract));
        
        string IMigrationMetadata.Id
        {
            get { return "201812171954530_added Description and deleted the icon delete in contract"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
