// <auto-generated />
namespace PrimePaper.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addeddetaileditanddeletemethod : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addeddetaileditanddeletemethod));
        
        string IMigrationMetadata.Id
        {
            get { return "201811292127471_added detail,edit and delete method"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
